### PR TITLE
Possible way to integrate Azure AAD oauth2 token validation into scimgateway

### PR DESCRIPTION
**Pull request by visualjeff**
**This pull request is just a suggestion.**  I suspect you may want to change it up a bit before introducing these changes into the code base.

1. Added dependency **azure-ad-jwt** for token validation.
2. Modified **config/plugin-testmode.js** file by added a property titled **authType**.  Which could be one of four values:  **noauth**, **basic**, **bearer**, **token**
3. Modified **lib/scimgateway.js** auth code so as to use a switch for handling authentication.

lib/scimgateway.js lines 142 to 152 do the heavy lifting for token validation.

I tested all four types of auths each worked fine.
Note the oauth2 token validation took place using Sync Fabric on Azure.  Its passed.

Jeff

PS.  Interesting note and confirmed with Microsoft.  The audience value will always be the same for Sync Fabric integrations.  The number I've provided references AAD and as of now will never differ.  Charley and myself and our contact at Microsoft feel like this is a security design flaw.  We all thought the audience should be the scimgateway app (a unique number).  Oh well...

### CODE REVIEW

**Comment by visualjeff** [comment]
I don't expect the build to pass because the tests will be looking to perform basic auth and what I submitted was an example of how to perform oauth2 token validation.

**Comment by jelhub** [comment]
This is interesting, oauth have been a missing part.

I will soon release a new version where testmode will be replaced by the lokijs that you previously provided - don't want to maintain two quite similar plugins and lokijs gives more flexibility

Will look into this one later on.

Thanks,
Jarle

**Comment by visualjeff** [comment]
Very cool.  I really didn't expect you to accept it but hopefully you'll be able to work in the oauth2 token validation code when the time is right.  Charley and I are testing what we have as an Azure App and any learnings we uncover will be passed back to you.  

Have a good weekend,

Jeff

**Comment by jelhub** [comment]
Hi,
JWT now implemented in v0.5.0
Decided to use the Microsoft supported passport-azure-ad package.

Thanks,
Jarle

**Pull request closed without merging**
