### PR TITLE
A plugin for lokijs. Includes configuration file and tests

### PR DESCRIPTION
**Pull request by visualjeff**
This lokijs plugin is for folks who would like to use a noSQL database.  Its a fast, in-memory document-oriented datastore for node.js.  Additionally it also can supports the use of adapters such as indexDB for larger datasets. 

See [http://lokijs.org/](http://lokijs.org/) for details.

Jeff

### CODE REVIEW

**Comment by jelhub** [comment]
Hi,
Thank you for showing new solutions, this is really great.

Maybe default settings for this one should be persistent store and not loading scimgateway test users? We then have an example of document oriented userstore located on the gateway using lokijs in-memory technology.

Seems indexDB/LokiIndexedAdapter is ment for browsers? It did work using nodejs only.

This seems to work:

let db = new loki('loki.json', {
    env: 'NODEJS',
    autoload: true,
    autoloadCallback : loadHandler,
    autosave: true, 
    autosaveInterval: 10000, // 10 seconds
 });

 function loadHandler() {
    // if database did not exist it will be empty so intitialize here
    items = db.getCollection('items');
    if (items === null) {
        items = db.addCollection('items');
    }
}

Challenge seems to be the asynchronous autoloadCallback. Need to put scimgateway pluging code in the loadHandler method to be able to use an existing database on startup?

Regarding test scripts, in the current version I extended your test script for plugin-testmode using end to end testing (get/post/patch instead of scimgateway.emit)

Thanks,
Jarle

**Comment by jelhub** [comment]
What about using plugin-loki.json. Something like:

endpoint: {
  "dbfile": "looki.json"
  "autoload": false,
  "autosave": false,
}

With this config the pluging should work like your existing code (test users loaded and no persistent storage). Setting autoload/autosave to true, should then use persisten storage and database file defined

Having "adapter: new loki.LokiMemoryAdapter()" defined in the code seems not to be needed? We only get persistent storage when autoload/autosave have been set.

Jarle

**Comment by jelhub** [comment]
endpoint: {
"dbfile": "looki.json"
"persistence": false
}

Setting autoload/autosave based on endpoint.persistence

Jarle

**Comment by visualjeff** [comment]
Hey Jarle,

Yes, you're correct about indexdb.  It wouldn't be a good fit.  My bad.   

Autoload with lokijs introduces a challenge.  If it was wrapped in Promise we could proceed in the following .then() with starting up the scimgateway.

BTW, I just happen to find the lokijs database rather interesting.   I can work on it a bit more and resubmit my pull request if you'd like?  There is no rush to get it in.

Jeff

**Comment by jelhub** [comment]
I have looked into it and almost done, but need some more testing before upload.
Jarle

**Pull request merged**
